applications:
  - path: ../
    memory: 512M
    instances: 1
    domain: de-cloudfoundry-check-cl.eu-de.containers.appdomain.cloud
    name: emotions-demo-highscore-tsuedbro
    host: emotions-demo-highscore-tsuedbro
    disk_quota: 1024M
